# Use an official Node.js image as the base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install dependencies (only package.json and yarn.lock are copied to optimize caching)
COPY package*.json ./

# Install the dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application code to the working directory
COPY . .

# Expose the default Next.js port, which can be overwritten by compose
ENV  PORT=3000
EXPOSE $PORT

# Run the Next.js development server
CMD ["yarn", "dev"]
